name: 构建镜像并推送到Docker hub
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm build 工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 登录Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 构建镜像并推送到Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 617qe/qe-react-app:latest
